const initialState = {
  categories: [
    { id: 'sneakers', name: 'Sneakers' },
    { id: 'tees', name: 'Tees' },
    { id: 'bags', name: 'Bags' },
    { id: 'chains', name: 'Chains' },
  ],
  products: [
    {
      id: 1,
      name: 'The coolest sneakers',
      description: 'Those are the coolest sneakers in the whole world! You won`t be able to find any coolest skeakers in your life',
      image: 'https://images.dsw.com/is/image/DSWShoes/409312_100_ss_01?$pdp-image$',
      category: 'sneakers',
      price: 30,
      isNew: false,
      comprasion: false,
      likes: 31,
      dislikes: 1,
    },
    {
      id: 2,
      name: 'The coolest sneakers',
      description: 'Those are the coolest sneakers in the whole world! You won`t be able to find any coolest skeakers in your life',
      image: 'https://images.dsw.com/is/image/DSWShoes/409312_100_ss_01?$pdp-image$',
      category: 'sneakers',
      price: 41,
      isNew: false,
      comprasion: false,
      likes: 23,
      dislikes: 7,
    },
    {
      id: 3,
      name: 'The coolest sneakers',
      description: 'Those are the coolest sneakers in the whole world! You won`t be able to find any coolest skeakers in your life',
      image: 'https://images.dsw.com/is/image/DSWShoes/409312_100_ss_01?$pdp-image$',
      category: 'sneakers',
      price: 25,
      isNew: false,
      comprasion: false,
      likes: 45,
      dislikes: 234,
    },
    {
      id: 4,
      name: 'The coolest sneakers',
      description: 'Those are the coolest sneakers in the whole world! You won`t be able to find any coolest skeakers in your life',
      image: 'https://images.dsw.com/is/image/DSWShoes/409312_100_ss_01?$pdp-image$',
      category: 'sneakers',
      price: 39,
      isNew: false,
      comprasion: false,
      likes: 36,
      dislikes: 1,
    },
    {
      id: 5,
      name: 'The coolest sneakers',
      description: 'Those are the coolest sneakers in the whole world! You won`t be able to find any coolest skeakers in your life',
      image: 'https://images.dsw.com/is/image/DSWShoes/409312_100_ss_01?$pdp-image$',
      category: 'sneakers',
      price: 30,
      isNew: false,
      comprasion: false,
      likes: 31,
      dislikes: 1,
    },
    {
      id: 6,
      name: 'The coolest sneakers',
      description: 'Those are the coolest sneakers in the whole world! You won`t be able to find any coolest skeakers in your life',
      image: 'https://images.dsw.com/is/image/DSWShoes/409312_100_ss_01?$pdp-image$',
      category: 'sneakers',
      price: 29.99,
      isNew: false,
      comprasion: false,
      likes: 31,
      dislikes: 1,
    },
    {
      id: 7,
      name: 'The coolest sneakers',
      description: 'Those are the coolest sneakers in the whole world! You won`t be able to find any coolest skeakers in your life',
      image: 'https://images.dsw.com/is/image/DSWShoes/409312_100_ss_01?$pdp-image$',
      category: 'sneakers',
      price: 54,
      isNew: false,
      comprasion: false,
      likes: 31,
      dislikes: 1,
    },
    {
      id: 8,
      name: 'The coolest sneakers',
      description: 'Those are the coolest sneakers in the whole world! You won`t be able to find any coolest skeakers in your life',
      image: 'https://images.dsw.com/is/image/DSWShoes/409312_100_ss_01?$pdp-image$',
      category: 'sneakers',
      price: 42.50,
      isNew: false,
      comprasion: false,
      likes: 31,
      dislikes: 1,
    },
    {
      id: 9,
      name: 'The coolest sneakers',
      description: 'Those are the coolest sneakers in the whole world! You won`t be able to find any coolest skeakers in your life',
      image: 'https://images.dsw.com/is/image/DSWShoes/409312_100_ss_01?$pdp-image$',
      category: 'sneakers',
      price: 35,
      isNew: false,
      comprasion: false,
      likes: 31,
      dislikes: 1,
    },
    {
      id: 10,
      name: 'The coolest sneakers',
      description: 'Those are the coolest sneakers in the whole world! You won`t be able to find any coolest skeakers in your life',
      image: 'https://images.dsw.com/is/image/DSWShoes/409312_100_ss_01?$pdp-image$',
      category: 'sneakers',
      price: 22.99,
      isNew: false,
      comprasion: false,
      likes: 31,
      dislikes: 1,
    },
    {
      id: 11,
      name: 'The coolest sneakers',
      description: 'Those are the coolest sneakers in the whole world! You won`t be able to find any coolest skeakers in your life',
      image: 'https://images.dsw.com/is/image/DSWShoes/409312_100_ss_01?$pdp-image$',
      category: 'sneakers',
      price: 26,
      isNew: false,
      comprasion: false,
      likes: 31,
      dislikes: 1,
    },
    {
      id: 12,
      name: 'The coolest sneakers',
      description: 'Those are the coolest sneakers in the whole world! You won`t be able to find any coolest skeakers in your life',
      image: 'https://images.dsw.com/is/image/DSWShoes/409312_100_ss_01?$pdp-image$',
      category: 'sneakers',
      price: 28,
      isNew: false,
      comprasion: false,
      likes: 31,
      dislikes: 1,
    },
    {
      id: 13,
      name: 'The coolest sneakers',
      description: 'Those are the coolest sneakers in the whole world! You won`t be able to find any coolest skeakers in your life',
      image: 'https://images.dsw.com/is/image/DSWShoes/409312_100_ss_01?$pdp-image$',
      category: 'sneakers',
      price: 34,
      isNew: false,
      comprasion: false,
      likes: 31,
      dislikes: 1,
    },
    {
      id: 14,
      name: 'The coolest sneakers',
      description: 'Those are the coolest sneakers in the whole world! You won`t be able to find any coolest skeakers in your life',
      image: 'https://images.dsw.com/is/image/DSWShoes/409312_100_ss_01?$pdp-image$',
      category: 'sneakers',
      price: 47,
      isNew: false,
      comprasion: false,
      likes: 31,
      dislikes: 1,
    },
    {
      id: 15,
      name: 'The coolest sneakers',
      description: 'Those are the coolest sneakers in the whole world! You won`t be able to find any coolest skeakers in your life',
      image: 'https://images.dsw.com/is/image/DSWShoes/409312_100_ss_01?$pdp-image$',
      category: 'sneakers',
      price: 56,
      isNew: false,
      comprasion: false,
      likes: 31,
      dislikes: 1,
    },
    {
      id: 16,
      name: 'The coolest sneakers',
      description: 'Those are the coolest sneakers in the whole world! You won`t be able to find any coolest skeakers in your life',
      image: 'https://images.dsw.com/is/image/DSWShoes/409312_100_ss_01?$pdp-image$',
      category: 'sneakers',
      price: 64,
      isNew: false,
      comprasion: false,
      likes: 31,
      dislikes: 1,
    },
    {
      id: 17,
      name: 'The coolest sneakers',
      description: 'Those are the coolest sneakers in the whole world! You won`t be able to find any coolest skeakers in your life',
      image: 'https://images.dsw.com/is/image/DSWShoes/409312_100_ss_01?$pdp-image$',
      category: 'sneakers',
      price: 39,
      isNew: false,
      comprasion: false,
      likes: 31,
      dislikes: 1,
    },
    {
      id: 18,
      name: 'The coolest sneakers',
      description: 'Those are the coolest sneakers in the whole world! You won`t be able to find any coolest skeakers in your life',
      image: 'https://images.dsw.com/is/image/DSWShoes/409312_100_ss_01?$pdp-image$',
      category: 'sneakers',
      price: 31,
      isNew: false,
      comprasion: false,
      likes: 31,
      dislikes: 1,
    },
    {
      id: 19,
      name: 'The coolest sneakers',
      description: 'Those are the coolest sneakers in the whole world! You won`t be able to find any coolest skeakers in your life',
      image: 'https://images.dsw.com/is/image/DSWShoes/409312_100_ss_01?$pdp-image$',
      category: 'sneakers',
      price: 46,
      isNew: false,
      comprasion: false,
      likes: 31,
      dislikes: 1,
    },
    {
      id: 20,
      name: 'The coolest sneakers',
      description: 'Those are the coolest sneakers in the whole world! You won`t be able to find any coolest skeakers in your life',
      image: 'https://images.dsw.com/is/image/DSWShoes/409312_100_ss_01?$pdp-image$',
      category: 'sneakers',
      price: 39.99,
      isNew: false,
      comprasion: false,
      likes: 31,
      dislikes: 1,
    },
    {
      id: 21,
      name: 'The coolest sneakers',
      description: 'Those are the coolest sneakers in the whole world! You won`t be able to find any coolest skeakers in your life',
      image: 'https://images.dsw.com/is/image/DSWShoes/409312_100_ss_01?$pdp-image$',
      category: 'sneakers',
      price: 47,
      isNew: false,
      comprasion: false,
      likes: 31,
      dislikes: 1,
    },
    {
      id: 22,
      name: 'The coolest sneakers',
      description: 'Those are the coolest sneakers in the whole world! You won`t be able to find any coolest skeakers in your life',
      image: 'https://images.dsw.com/is/image/DSWShoes/409312_100_ss_01?$pdp-image$',
      category: 'sneakers',
      price: 54,
      isNew: false,
      comprasion: false,
      likes: 31,
      dislikes: 1,
    },

    {
      id: 23,
      name: 'The coolest sneakers',
      description: 'Those are the coolest sneakers in the whole world! You won`t be able to find any coolest skeakers in your life',
      image: 'https://images.dsw.com/is/image/DSWShoes/409312_100_ss_01?$pdp-image$',
      category: 'sneakers',
      price: 43,
      isNew: false,
      comprasion: false,
      likes: 31,
      dislikes: 1,
    },
    {
      id: 24,
      name: 'The coolest sneakers',
      description: 'Those are the coolest sneakers in the whole world! You won`t be able to find any coolest skeakers in your life',
      image: 'https://images.dsw.com/is/image/DSWShoes/409312_100_ss_01?$pdp-image$',
      category: 'sneakers',
      price: 61,
      isNew: false,
      comprasion: false,
      likes: 31,
      dislikes: 1,
    },
    {
      id: 25,
      name: 'The coolest sneakers',
      description: 'Those are the coolest sneakers in the whole world! You won`t be able to find any coolest skeakers in your life',
      image: 'https://images.dsw.com/is/image/DSWShoes/409312_100_ss_01?$pdp-image$',
      category: 'sneakers',
      price: 55,
      isNew: false,
      comprasion: false,
      likes: 31,
      dislikes: 1,
    },
    {
      id: 26,
      name: 'The coolest sneakers',
      description: 'Those are the coolest sneakers in the whole world! You won`t be able to find any coolest skeakers in your life',
      image: 'https://images.dsw.com/is/image/DSWShoes/409312_100_ss_01?$pdp-image$',
      category: 'sneakers',
      price: 36,
      isNew: false,
      comprasion: false,
      likes: 31,
      dislikes: 1,
    },
    {
      id: 27,
      name: 'The coolest sneakers',
      description: 'Those are the coolest sneakers in the whole world! You won`t be able to find any coolest skeakers in your life',
      image: 'https://images.dsw.com/is/image/DSWShoes/409312_100_ss_01?$pdp-image$',
      category: 'sneakers',
      price: 19.99,
      isNew: false,
      comprasion: false,
      likes: 31,
      dislikes: 1,
    },
    {
      id: 28,
      name: 'The coolest sneakers',
      description: 'Those are the coolest sneakers in the whole world! You won`t be able to find any coolest skeakers in your life',
      image: 'https://images.dsw.com/is/image/DSWShoes/409312_100_ss_01?$pdp-image$',
      category: 'sneakers',
      price: 59.99,
      isNew: false,
      comprasion: false,
      likes: 31,
      dislikes: 1,
    },
    {
      id: 29,
      name: 'The coolest sneakers',
      description: 'Those are the coolest sneakers in the whole world! You won`t be able to find any coolest skeakers in your life',
      image: 'https://images.dsw.com/is/image/DSWShoes/409312_100_ss_01?$pdp-image$',
      category: 'sneakers',
      price: 51,
      isNew: false,
      comprasion: false,
      likes: 31,
      dislikes: 1,
    },
    {
      id: 30,
      name: 'The coolest sneakers',
      description: 'Those are the coolest sneakers in the whole world! You won`t be able to find any coolest skeakers in your life',
      image: 'https://images.dsw.com/is/image/DSWShoes/409312_100_ss_01?$pdp-image$',
      category: 'sneakers',
      price: 34.99,
      isNew: false,
      comprasion: false,
      likes: 31,
      dislikes: 1,
    },
  ],
  promo: [
    { id: 1, productId: 7, sale: 10 },
    { id: 2, productId: 11, sale: 5 },
    { id: 3, productId: 26, sale: 50 },
  ],
  bestsellers: [
    { id: 1, productId: 4 },
    { id: 2, productId: 15 },
    { id: 3, productId: 27 },
  ]
}

export default initialState;